### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by KinoLab07** [maxgerhardt/rotary-encoder-over-mcp23017#15]
Hi, I'm quite new in arduino... I'm on OsX system and when i try to install the library in the standard way (directly with the .zip file) I receive this error:
![Captura de pantalla 2023-08-14 a la(s) 7 49 07 p m](https://github.com/maxgerhardt/rotary-encoder-over-mcp23017/assets/117310638/6154816d-46a0-42c1-8e12-db72985432f1)

So, there is a particular way for install this library... 

Thx for your works

**Comment by maxgerhardt** [comment]
I've never in my life seen PlatformIO throw such an error message. Is that the Arduino IDE 2.0 or PlatformIO? Because this repository is **not** a Arduino IDE library, it's a PlatformIO firmware project. To install it in the Arduino IDE, you have to copy the library folders from https://github.com/maxgerhardt/rotary-encoder-over-mcp23017/tree/master/lib in `<User folder>\Arduino\libraries`, then create a new sketch and save it, then in the same folder as the sketch (.ino) file, add the https://github.com/maxgerhardt/rotary-encoder-over-mcp23017/blob/master/src/RotaryEncOverMCP.h file.

**Comment by KinoLab07** [comment]
Ok... Thk...
The Error above comes from Arduino IDE not PlatformIO...
Now how can I try with one encoder..
When I open the empty scketch that I've created, it open the .h file too... but i don't know how test if the encoder works as midi... Sorry but I'm newer and learning with the Arduino

**Comment by maxgerhardt** [comment]
The one MCP23017 chip + one rotary encoder circuit is shown in https://github.com/maxgerhardt/rotary-encoder-over-mcp23017#circuits.

That hardware setup also means you can use https://github.com/maxgerhardt/rotary-encoder-over-mcp23017/blob/master/examples/Polling/PollingExample.cpp without any adaptations. It just declares one rotary encoder on the chip's GPA7, GPA6 pins.

Also note that you can look into the datasheet (https://ww1.microchip.com/downloads/en/devicedoc/20001952c.pdf) at any time to see the pinout of the chip. But you might not have the bare chip and a module with the chip instead where all the pins are labeled.

**Comment by KinoLab07** [comment]
okkkk... I've copy the pollingExample.cpp in the same directory of the .ino, and when I try to verify I receive this error
![Captura de pantalla 2023-08-15 a la(s) 2 41 49 p m](https://github.com/maxgerhardt/rotary-encoder-over-mcp23017/assets/117310638/94140c7e-06dd-4fd8-b8ee-4331b10c130e)

**Comment by maxgerhardt** [comment]
Then you didn't copy the RotaryEncOverMCP.h file in the same folder as your sketch file.

Open `/Users/kinolab07/Desktop/Moog M15/Sketch_RotraryMcp23017/sketch_rotary_mcp23017/` in your Finder and copy in https://github.com/maxgerhardt/rotary-encoder-over-mcp23017/blob/master/src/RotaryEncOverMCP.h.

**Comment by KinoLab07** [comment]
Yes is inside the folder
![Captura de pantalla 2023-08-15 a la(s) 2 47 39 p m](https://github.com/maxgerhardt/rotary-encoder-over-mcp23017/assets/117310638/ec011de7-37c0-431c-8863-8d68fa080e83)

**Comment by maxgerhardt** [comment]
Oh? Weird. Well first of all, having both the `PollingExample.cpp` and the `.ino` file is very weird, you should delte one of them and put the content of https://github.com/maxgerhardt/rotary-encoder-over-mcp23017/blob/master/examples/Polling/PollingExample.cpp in the one remaining file.

Does the error change when you use
```
#include "RotaryEncOverMCP.h"
```
instead of `#include <RotaryEncOverMCP.h>`?

**Comment by KinoLab07** [comment]
With this #include "RotaryEncOverMCP.h" the error disappear...
Now everything works in the Serial monitor perfect... Thx...

Now the problem is that when I conect the Arduino UNO as Midi in the moog app, it recognize the board but the rotary encoder move all the knobs in a caothic way... So, I've to check this problem now...

Anyway... thx for your help

**Comment by maxgerhardt** [comment]
The `PollingExample` sketch is just a very basic test. There isn't anything in that code to interact with anything MIDI. You would have to combine the codes as needed.

**Comment by maxgerhardt** [comment]
In any case, since you see that the rotary encoder is working in the serial monitor with the test sketch, this library's purpose is fullfilled and there's no issue with it.
